spring:
  application:
    name: ms-course-management
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
logging:
  level:
    org.hibernate.SQL: debug
